In [8]:
import torch

In [11]:
x = torch.empty(2, 3, 4)
x

tensor([[[ 1.0803e+31,  3.0255e+29, -1.7132e+16,  1.1024e+24],
         [ 1.7224e+22,  2.7903e+20,  2.5353e+30,  1.9758e-43],
         [ 1.8033e+28,  1.7615e+19,  4.5029e+24,  2.8269e+23]],

        [[ 2.9972e+32,  1.0680e+25,  7.7783e+31,  1.1024e+24],
         [ 1.7224e+22,  3.0299e+32,  2.8880e-39,  5.1245e-20],
         [ 2.5353e+30,  4.4842e-44,  1.7911e+25,  1.0303e+21]]])

In [12]:
torch.rand(2, 2)

tensor([[0.0146, 0.7835],
        [0.6719, 0.2520]])

In [13]:
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [14]:
torch.ones(5, 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [15]:
x.dtype

torch.float32

In [18]:
x = torch.ones(2, 2, dtype = torch.double)
x.dtype

torch.float64

In [20]:
x.size()

torch.Size([2, 2])

In [21]:
torch.tensor([2.4, 0.03])

tensor([2.4000, 0.0300])

In [22]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
torch.add(a, b)

tensor([[1.0825, 1.1503],
        [0.5974, 0.5256]])

In [23]:
print(b)
# Inplace operations, modify tensor
b.add_(a)
print(b)

tensor([[0.4185, 0.9513],
        [0.2061, 0.4497]])
tensor([[1.0825, 1.1503],
        [0.5974, 0.5256]])


In [24]:
z = torch.rand(5, 3)

In [25]:
z

tensor([[0.1133, 0.2832, 0.3891],
        [0.5611, 0.8091, 0.8725],
        [0.1792, 0.9086, 0.7966],
        [0.1884, 0.7891, 0.7183],
        [0.6100, 0.2115, 0.2220]])

In [28]:
z[:, -2]

tensor([0.2832, 0.8091, 0.9086, 0.7891, 0.2115])

In [29]:
z = torch.rand(4, 4)
#reshape
z

tensor([[0.7666, 0.4762, 0.5829, 0.4158],
        [0.3738, 0.5903, 0.6731, 0.6864],
        [0.4441, 0.6826, 0.3200, 0.8039],
        [0.9879, 0.1574, 0.4983, 0.7811]])

In [30]:
z_resized = z.view(16)
z_resized

tensor([0.7666, 0.4762, 0.5829, 0.4158, 0.3738, 0.5903, 0.6731, 0.6864, 0.4441,
        0.6826, 0.3200, 0.8039, 0.9879, 0.1574, 0.4983, 0.7811])

In [31]:
z.view(8, 2)

tensor([[0.7666, 0.4762],
        [0.5829, 0.4158],
        [0.3738, 0.5903],
        [0.6731, 0.6864],
        [0.4441, 0.6826],
        [0.3200, 0.8039],
        [0.9879, 0.1574],
        [0.4983, 0.7811]])

In [35]:
# -1 to not specify one dimesion
z.view(2, -1)

tensor([[0.7666, 0.4762, 0.5829, 0.4158, 0.3738, 0.5903, 0.6731, 0.6864],
        [0.4441, 0.6826, 0.3200, 0.8039, 0.9879, 0.1574, 0.4983, 0.7811]])

In [36]:
import numpy as np

In [37]:
a = torch.ones(5)

In [38]:
a

tensor([1., 1., 1., 1., 1.])

In [39]:
b = a.numpy()
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [40]:
type(b)

numpy.ndarray

In [41]:
b+=1

In [42]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [43]:
x = torch.ones(5, requires_grad = True)

In [44]:
x

tensor([1., 1., 1., 1., 1.], requires_grad=True)

In [45]:
y = x + 6
z = y*y
z.backward()

RuntimeError: grad can be implicitly created only for scalar outputs